apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hbase-connector.fullname" . }}-config
  labels:
    {{- include "hbase-connector.labels" . | nindent 4 }}
data:
  hbase-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hbase.zookeeper.quorum</name>
        <value>{{ .Values.zookeeper.quorum }}</value>
      </property>
      <property>
        <name>hbase.replication</name>
        <value>true</value>
      </property>
    </configuration>
  kafka-route-rules.xml: |
    <rules>
      <rule action="route" table="default:table" topic="test-topic" />
      <rule action="route" topic="test-topic" />
    </rules>
  kafka.properties: |
    bootstrap.servers={{ .Values.kafka.broker }}
    max.request.size=16000000