
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dsync.fullname" $ }}-config
  labels:
    app: {{ include "dsync.name" $ }}
data:
  {{ (.Files.Glob "config_files/*").AsConfig | nindent 4 }}
